export const listOfObjects = [
    {
        Title: "ARCo",
        Handle: "V12 Diesel-Electric",
        ImageURL: "../img/arco.png",
        Description: "Cargo diesel-electric locomotive. 7.5 wide. Modular engine and cabs. Fully L-gauge compatible. 9V only.",
        Stock: 3,
        code: 5,
        pid: 1,
        price:150,
        category:"prebuilt",
        pieces: 1901,
        motorizable: true,
        lighting:true,
        wheelArrangement:"Bo-Bo",
    },
    {
        Title: "Siemens ARX",
        Handle: "Electric @ 15kV",
        ImageURL: "../img/siemens.png",
        Description: "High-speed electric locomotive. Dual 9V motor compatible. 8+ wide. Monolythic cars with detailed engine rooms and cabs.",
        Stock: 11,
        code: 5,
        pid: 2,
        price:170,
        category:"blueprint",
        pieces: 2150,
        motorizable: true,
        lighting:false,
        wheelArrangement:"Co-Co",        
    },
    {
        Title: "Alstom 1121",
        Handle: "I16 Diesel-Electric",
        ImageURL: "../img/alstom.png",
        Description: "French style diesel-electric locomotive. Modular cabs and engines. 7.5 studs wide. PF/PU compatible.",
        Stock: 10,
        code: 4,
        pid: 3,
        price:190,
        category:"user",
        pieces: 1440,
        motorizable: true,
        lighting:true,
        wheelArrangement:"Bo-Bo",
    },
    {
        Title: "JRF C121",
        Handle: "Electric @17kV/I12 Diesel-Electric",
        ImageURL: "../img/jrf_all_dualend.png",
        Description: "Dual duty electric/diesel-electric locomotive. Modular cab and engine. 7.5 studs wide. PF and 9V compatible.",
        Stock: 6,
        code: 4,
        pid: 4,
        price:185,
        category:"blueprint",
        pieces: 877,
        motorizable: true,
        lighting:false,
        wheelArrangement:"Bo-Bo",
    },
    {
        Title: "SKMWCo Shunter",
        Handle: "Diesel-hydraulic",
        ImageURL: "../img/shunt2d.png",
        Description: "Shunt duty locomotive. Diesel-hydraulic classic shunter. 7 studs wide. Not motorizable, display only.",
        Stock: 1,
        code: 1,
        pid: 5,
        price:145,
        category:"user",
        pieces: 176,
        motorizable: true,
        lighting:true,
        wheelArrangement:"Bo",
    },
    {
        Title: "Toshiba EMU",
        Handle: "Electric @ 28kV",
        ImageURL: "../img/toshiba.png",
        Description: "Passenger cars based on the 1960s classic Toshiba body. 7 wide. Not motorizable. Includes two cars.",
        Stock: 6,
        code: 4,
        pid: 6,
        price:145,
        category:"prebuilt",
        pieces: 2017,
        motorizable: true,
        lighting:true,
        wheelArrangement:"Bo-Bo",
    },
    {
        Title: "Siemens MEC",
        Handle: "Electric @ multi",
        ImageURL: "../img/metcar.png",
        Description: "Passenger EMU. Two cars included. Motorizable only in 9v. 6.5 wide. Fully furnished interior. Seats 10 minifigs. Stands 15 mini figs.",
        Stock: 9,
        code: 5,
        pid: 7,
        price:145,
        category:"prebuilt",
        pieces: 1190,
        motorizable: true,
        lighting:true,
        wheelArrangement:"Bo-Bo",
    },
    {
        Title: "MRC Light rail EMU",
        Handle: "Electric @ multi",
        ImageURL: "../img/xlightrail.png",
        Description: "Permanently coupled EMU. Motorizable only in 9v. 6.5 wide. Features a fully furnished interior.",
        Stock: 0,
        code: 3,
        pid: 8,
        price:145,
        category:"blueprint",
        pieces: 692,
        motorizable: true,
        lighting:true,
        wheelArrangement:"Bo-Bo-Bo",
    },
    {
        Title: "MRC Boxcar Shunter",
        Handle: "Diesel-electric",
        ImageURL: "../img/boxshunt.png",
        Description: "Diesel electric shunt. Motorizable only in 9v. 7 stud wide. Features fully furnished cabs and engine bay.",
        Stock: 6,
        code: 2,
        pid: 9,
        price:120,
        category:"blueprint",
        pieces: 267,
        motorizable: true,
        lighting:true,
        wheelArrangement:"Bo",
    },
    {
        Title: "MRC Long-hood Shunter",
        Handle: "Diesel-hydraulic",
        ImageURL: "../img/shuntlh.png",
        Description: "Diesel electric shunt. Motorizable only in 9v. 7 stud wide. Features fully furnished cabs and engine bay.",
        Stock: 9,
        code: 2,
        pid: 10,
        price:145,
        category:"prebuilt",
        pieces: 201,
        motorizable: true,
        lighting:true,
        wheelArrangement:"Bo",
    },
    {
        Title: "ODD R-1250 ",
        Handle: "Diesel-hydraulic",
        ImageURL: "../img/oddrail.png",
        Description: "Diesel electric cargo duty locomotive. Motorizable only in 9v. 7 stud wide. Ocean lines livery. Features fully furnished cab.",
        Stock: 3,
        code: 4,
        pid: 11,
        price:160,
        category:"prebuilt",
        pieces: 311,
        motorizable: true,
        lighting:false,
        wheelArrangement:"Bo-Bo",
    },
    {
        Title: "ARCo HSP ",
        Handle: "Dual electric/Diesel-electric",
        ImageURL: "../img/arco_hsp.png",
        Description: "Dual duty electric/diesel-electric locomotive. Modular cab and engine. 7.5 studs wide. PF and 9V compatible. Features fully furnished cab.",
        Stock: 3,
        code: 5,
        pid: 12,
        price:230,
        category:"special",
        pieces: 1991,
        motorizable: true,
        lighting:true,
        wheelArrangement:"Bo-Bo",
    },
    {
        Title: "ARCo DDF",
        Handle: "Diesel-electric",
        ImageURL: "../img/arco_ddf.png",
        Description: "Diesel electric cargo duty locomotive. Motorizable only in 9v. 7 stud wide. Redboy Transport Co. livery. Features fully furnished cab.",
        Stock: 3,
        code: 3,
        pid: 13,
        price:145,
        category:"special",
        pieces: 584,
        motorizable: true,
        lighting:true,
        wheelArrangement:"Bo-Bo",
    },
    {
        Title: "Alstom 1934",
        Handle: "Diesel-electric",
        ImageURL: "../img/alstom1934.png",
        Description: "Diesel electric cargo duty locomotive. 8.5 stud wide. Trans Continental Lines livery. Features fully furnished cab, engine room and tanks. Motorizable only in 9v." ,
        Stock: 3,
        code: 5,
        pid: 14,
        price:180,
        category:"special",
        pieces: 1058,
        motorizable: true,
        lighting:true,
        wheelArrangement:"Co-Co",
    },
    {
        Title: "Panoramic Pullman",
        Handle: "Unpowered passenger car",
        ImageURL: "../img/dbldkr.png",
        Description: "Double deck passenger car with restaurant layout. Seats 10 minifigs. 6 studs wide. Unpowered. German ICE livery.",
        Stock: 3,
        code: 1,
        pid: 15,
        price:115,
        category:"user",
        pieces: 192,
        motorizable: false,
        lighting: false,
        wheelArrangement:"Unpowered 2-axle",
    },
];

